-- DROP SCHEMA public;

CREATE SCHEMA public AUTHORIZATION collection_user;

-- DROP SEQUENCE public.bids_id_seq;

CREATE SEQUENCE public.bids_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.collection_items_id_seq;

CREATE SEQUENCE public.collection_items_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.hotwheels_id_seq;

CREATE SEQUENCE public.hotwheels_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.listings_id_seq;

CREATE SEQUENCE public.listings_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.users_id_seq;

CREATE SEQUENCE public.users_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.wishlist_items_id_seq;

CREATE SEQUENCE public.wishlist_items_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;-- public.hotwheels definition

-- Drop table

-- DROP TABLE public.hotwheels;

CREATE TABLE public.hotwheels (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	code varchar(255) NOT NULL,
	color varchar(255) NULL,
	image_url varchar(255) NULL,
	"name" varchar(255) NULL,
	series varchar(255) NULL,
	"year" varchar(255) NULL,
	CONSTRAINT hotwheels_code_key UNIQUE (code),
	CONSTRAINT hotwheels_pkey PRIMARY KEY (id)
);


-- public.users definition

-- Drop table

-- DROP TABLE public.users;

CREATE TABLE public.users (
	balance float8 NULL,
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	email varchar(255) NULL,
	keycloak_id varchar(255) NOT NULL,
	CONSTRAINT users_keycloak_id_key UNIQUE (keycloak_id),
	CONSTRAINT users_pkey PRIMARY KEY (id)
);


-- public.collection_items definition

-- Drop table

-- DROP TABLE public.collection_items;

CREATE TABLE public.collection_items (
	acquired_date date NULL,
	ask_price numeric(10, 2) NULL,
	hotwheel_id int8 NOT NULL,
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	user_id int8 NOT NULL,
	availability varchar(255) NOT NULL,
	"condition" varchar(255) NOT NULL,
	notes varchar(255) NULL,
	visibility varchar(255) NOT NULL,
	CONSTRAINT collection_items_availability_check CHECK (((availability)::text = ANY ((ARRAY['NOT_FOR_SALE'::character varying, 'FOR_SALE'::character varying, 'ASK_ME'::character varying])::text[]))),
	CONSTRAINT collection_items_pkey PRIMARY KEY (id),
	CONSTRAINT collection_items_visibility_check CHECK (((visibility)::text = ANY ((ARRAY['PRIVATE'::character varying, 'PUBLIC'::character varying])::text[]))),
	CONSTRAINT fkkj90amyt8h6y529xwqpaqvbkf FOREIGN KEY (hotwheel_id) REFERENCES public.hotwheels(id),
	CONSTRAINT fkqbqdudvmw7hwi6ijdfg2vtrq4 FOREIGN KEY (user_id) REFERENCES public.users(id)
);


-- public.listings definition

-- Drop table

-- DROP TABLE public.listings;

CREATE TABLE public.listings (
	current_bid float8 NULL,
	price float8 NULL,
	created_at timestamp(6) NULL,
	end_date timestamp(6) NULL,
	highest_bidder_id int8 NULL,
	hotwheel_id int8 NULL,
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	seller_id int8 NULL,
	status varchar(255) NULL,
	"type" varchar(255) NULL,
	CONSTRAINT listings_pkey PRIMARY KEY (id),
	CONSTRAINT listings_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'SOLD'::character varying, 'CANCELLED'::character varying])::text[]))),
	CONSTRAINT listings_type_check CHECK (((type)::text = ANY ((ARRAY['FIXED'::character varying, 'AUCTION'::character varying])::text[]))),
	CONSTRAINT fk1fsedihdsq87mfbrm3xdss4pe FOREIGN KEY (highest_bidder_id) REFERENCES public.users(id),
	CONSTRAINT fkalvw7p9i5do4aw9o67h4gjucw FOREIGN KEY (hotwheel_id) REFERENCES public.hotwheels(id),
	CONSTRAINT fkdfglshentvek3cnsr7a4nwh7j FOREIGN KEY (seller_id) REFERENCES public.users(id)
);


-- public.wishlist_items definition

-- Drop table

-- DROP TABLE public.wishlist_items;

CREATE TABLE public.wishlist_items (
	max_price numeric(10, 2) NULL,
	priority int4 NOT NULL,
	created_at timestamptz(6) NOT NULL,
	hotwheel_id int8 NOT NULL,
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	user_id int8 NOT NULL,
	CONSTRAINT uk_wishlist_user_hotwheel UNIQUE (user_id, hotwheel_id),
	CONSTRAINT wishlist_items_pkey PRIMARY KEY (id),
	CONSTRAINT fk48qd79tsofoie08ten4i7shmr FOREIGN KEY (hotwheel_id) REFERENCES public.hotwheels(id),
	CONSTRAINT fkmmj2k1i459yu449k3h1vx5abp FOREIGN KEY (user_id) REFERENCES public.users(id)
);


-- public.bids definition

-- Drop table

-- DROP TABLE public.bids;

CREATE TABLE public.bids (
	amount float8 NOT NULL,
	bidder_id int8 NOT NULL,
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	listing_id int8 NOT NULL,
	"timestamp" timestamp(6) NOT NULL,
	CONSTRAINT bids_pkey PRIMARY KEY (id),
	CONSTRAINT fkk28ddqcmd0axg8bne1xleql7i FOREIGN KEY (listing_id) REFERENCES public.listings(id),
	CONSTRAINT fkmtrc6tnwawlpk1u2km6qnxbha FOREIGN KEY (bidder_id) REFERENCES public.users(id)
);